### PR TITLE
NixOS 23.11

### PR DESCRIPTION
**Pull request by minijackson**
This switches nixpkgs from the nixos-23.05 branch to nixos-23.11.

Several new things:

- NixOS 23.11 has the `quartoMinimal` packages, which is way smaller, because it does not depend on Java, Python, R. With dependencies, its 434MiB vs 2.7GiB

- NixOS uses `_FORTIFY_SOURCE=3` by default for extra buffer checks, but this caused an issue with epics-base (see commit)

- Some upstream Kafka options changed, and also now support Kraft mode. We use that for the integration test, and as a recommended way in the documentation. This removes the need for Zookeeper, and so frees port 8080.

cc @Rider128

### CODE REVIEW

**Review by stephane-cea — APPROVED** [review]
This looks good to me!

**Comment by Synthetica9** [comment]
> NixOS uses _FORTIFY_SOURCE=3 by default for extra buffer checks, but this caused an issue with epics-base (see commit)

Is this issue known about upstream? Is it a false positive added by the compiler or a real issue that just doesn't happen to give unwanted results?

**Review by lcaouen — APPROVED** [review]
Kafka Kraft-mode tested.
It works.

**Comment by minijackson** [comment]
@Synthetica9 FYI the `_FORTIFY_SOURCE=3` issue is being tracked in https://github.com/epics-base/epics-base/issues/514 and hopefully fixed in https://github.com/epics-base/epics-base/pull/517

**Pull request merged**
