### PR TITLE
support.mrfioc2: 2.6.0 -> 2.7.1

### PR DESCRIPTION
**Pull request by vivienCEA**

### CODE REVIEW

**Comment by agaget** [comment]
I approve

**Review by agaget — APPROVED** [review]

**Review by minijackson — CHANGES_REQUESTED** [review]
The tests don't pass because this also changes the mrf kernel driver version.

You need to remove the patch that is applied there, because it's now included in mrfioc2 2.7.0+:

https://github.com/epics-extensions/EPNix/blob/master/pkgs/epnix/kernel-modules/mrf/default.nix#L12-L20

**Comment by vivienCEA** [comment]
I remove the patch from kernel modules mrf and squash my commits

**Review by minijackson — APPROVED** [review]
Tests pass! Thanks a lot!

**Pull request merged**
